version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Devops_test
      MYSQL_USER: reda
      MYSQL_PASSWORD: reda
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

  app:
    build: .
    container_name: express_app
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: 
      DB_NAME: Devops_test
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["sh", "-c", "npx sequelize db:migrate && npm start"]

volumes:
  mysql_data:
